DjangoApp/urls.py
"""
Definition of urls for DjangoApp.
"""

from datetime import datetime
from django.conf.urls import url
# from app.forms import BootstrapAuthenticationForm
# from app.views import *
# from app.models import *
# from django.contrib.auth.views import *


# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
     
#     url(r'^$', home, name='home'),
#     url(r'^contact$', contact, name='contact'),
#     url(r'^about', about, name='about'),
#    url(r'^login/$', login, {
#             'template_name': 'app/login.html',
#             'authentication_form': BootstrapAuthenticationForm,
#             'extra_context':
#             {
#                 'title':'Log in',
#                 'year':datetime.now().year,
#             }
#         },
#         name='login'),
#        url(r'^logout$', logout, {  'next_page': '/'  },        name='logout')

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
]

# Use include() to add URLS from the catalog application 
from django.conf.urls import include

urlpatterns += [
    url(r'^home/', include('home.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^resources/', include('resources.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True)),
]


# Use static() to add url mapping to serve static files during development (only) 
#### I KNOW IT ONLY SAYS DURING DEVELOPMENT BUT I DONT KNOW WHERE ELSE TO PUT STATIC FILES (CSS)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#add image directory
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

uaMachineLearn/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application 
from django.conf.urls import include

urlpatterns += [
    url(r'^home/', include('home.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^resources/', include('resources.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#add image directory
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

from django.forms import ModelForm

# Create your models here.
# e-mail notification model
class Newsletter(models.Model):
    email = models.EmailField(max_length=254)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    def __str__(self):
        return self.email
	
class Schedule(models.Model): 
    date = models.DateField('Date')
    desc = models.TextField('Description',max_length=10000)
    loc = models.CharField('Location',max_length=1000)
    def __str__(self):
        return self.date.strftime("%d/%m/%y") + " Description: " + self.desc;      
		
class NewsletterForm(ModelForm):
    class Meta:
        model = Newsletter
        labels = { 
            "email" : "E-Mail",
            "firstName" : "First Name",
            "lastName" : "Last Name",
        }
        fields = '__all__'

home/forms.py
from django import forms

from .models import Newsletter

class NewsletterForm(ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
# from .models import Book, Author, BookInstance, Genre
from .models import NewsletterForm
from .models import Schedule

def index(request):
    # Render the HTML template index.html with the data in the context variable
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NewsletterForm(request.POST,)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            form.save()
            return render(request, 'thankYou.html', context={})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NewsletterForm()
    
    schedule_list = Schedule.objects.order_by('date')
    context = { 'emailForm' : form, 'schedule_list': schedule_list, }
    return render(
        request,
        'index.html',
        context,
    )

home/templates/base_generic.html
<!--

	Developed by Univ. of Alabama AI Club Website Team 2017
	Jordan Elizaga, jelizaga@crimson.ua.edu
	Alex Luong, aluong@crimson.ua.edu
-->

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>AI Club</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.3/css/bulma.min.css"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>

	<!-- Add additional CSS in static file -->
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/navigation.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	
	<!-- Add additional APP-SPECIFIC CSS in static file -->
	{% block styles %}
	{% endblock %}

</head>
<body>

	<!-- Navbar -->
	<nav class="navbar" role="navigation" aria-label="main navigation">
  	<div class="container">
  		<div class="navbar-brand">
  			<img src="{% static 'images/ua-square-logo.png' %}" alt="UA Logo">
    		<p class="logo navbar-item is-hidden-mobile">Artificial Intelligence & Machine Learning Club</p>
    		<p class="logo navbar-item is-hidden-tablet">AI & ML Club</p>
    		<button class="button navbar-burger is-hidden-tablet">
  				<span></span><span></span><span></span>
  			</button>
  		</div>

  		<div class="navbar-menu">
  			<div class="navbar-end is-hidden-tablet">
			  	<a class="navbar-item" href="{% url 'index' %}"><span class="icon"><i class="fa fa-home"></i></span> Home</a>
			  	<a class="navbar-item" href="{% url 'about' %}"><span class="icon"><i class="fa fa-info-circle"></i></span> About Us</a>
				  <a class="navbar-item" href="{% url 'resources' %}"><span class="icon"><i class="fa fa-folder-open"></i></span> Resources</a>
				  <a class="navbar-item" href="{% url 'contact' %}"><span class="icon"><i class="fa fa-address-book-o"></i></span> Contact</a>
				  <a class="navbar-item" href="{% url 'events' %}"><span class="icon"><i class="fa fa-calendar-o"></i></span> Events</a>
				  <a class="navbar-item" href="{% url 'projects' %}"><span class="icon"><i class="fa fa-briefcase"></i></span> Projects</a>
  			</div>
  		</div>
  	</div>
	</nav>

	<div class="container">
		<div class="columns">

			<!-- Sidebar Menu -->
			<div class="column section is-3 is-hidden-mobile">
				<aside class="menu">
			  	<p class="menu-label">General</p>
			  	<ul class="menu-list">
			  	  <li><a href="{% url 'index' %}"><span class="icon is-small"><i class="fa fa-home"></i></span> Home</a></li>
			  	  <li><a href="{% url 'about' %}"><span class="icon is-small"><i class="fa fa-info-circle"></i></span> About Us</a></li>
			  	  <li><a href="{% url 'resources' %}"><span class="icon is-small"><i class="fa fa-folder-open"></i></span> Resources</a></li>
			 	  	<li><a href="{% url 'contact' %}"><span class="icon is-small"><i class="fa fa-address-book-o"></i></span> Contact</a></li>
			 	  	<li><a href="{% url 'events' %}"><span class="icon is-small"><i class="fa fa-calendar-o"></i></span> Events</a></li>
			  	</ul>
			  	<p class="menu-label">Projects</p>
			  	<ul class="menu-list">
				  	<li><a href="{% url 'projects' %}"><span class="icon is-small"><i class="fa fa-briefcase"></i></span> Projects</a></li>
				    <li id="dropdown" class="dropdown">
    	  			<a id="trigger" aria-haspopup="true" aria-controls="dropdown-menu">
    	  				<span class="icon is-small"><i class="fa fa-files-o"></i></span>
    	  				<span> Lists</span>
    	  				<span class="icon is-small"><i class="fa fa-angle-down" aria-hidden="true"></i></span>
    	  			</a>
    	  			<ul class="dropdown-menu" id="dropdown-menu" role="menu">
    	  				<li><a>Project 1</a></li>
    	  				<li><a>Project 2</a></li>
    	  				<li><a>Project 3</a></li>
    	  			</ul>
				    </li>
				  </ul>
				</aside>
			</div>

			<!-- Page Content -->
			{% block content %}{% endblock %}			
			
		</div>
	</div>

	<footer>
		<div class="seperator"></div>
		<div class="container">
			<p>Connect with us via social media to stay up-to-date with the latest news.</p>
			<ul class="social">
				<li class="social-icon">
					<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
				</li>
				<li class="facebook social-icon">
					<a href="#"><i class="fa fa-facebook"></i></a>
				</li>
			</ul>
		</div>
	</footer>
</body>
</html>

home/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

{% comment %}
<h1>UA Artificial Intelligence &amp; Machine Learning Club </h1>
<p>Welcome to the <strong>University of Alabama: Artificial Intelligence and Machine Learning [AI/ML] club</strong>. Join our growing club and participate in projects that interest you: mathematics, business, finance, science, and art. Interested in something else? Suggest a project, all majors are welcome! </p>
<p> This site is under construction: if you would like to contribute to this growing website, feel free to contact me at: <br><u>jelizaga@crimson.ua.edu</u></p>
<p> Prereq's: NONE! If you aspire to learn web development and design, we can help get you up to speed :-) </p>

<form action="" method="post">
  {% csrf_token %}
  {{ emailForm }}    
  <input type="submit" value="Add me!">
</form>
{% endcomment %}

			<div class="column section">

				<!-- Home -->
				<!-- <h1 class="title is-3">Home</h1> -->
				<nav class="breadcrumb is-large" aria-label="breadcrumbs">
				  <ul>
				    <li><a class="title is-4" href="{% url 'index' %}">AI & ML Club</a></li>
				    <li class="is-active">
				    	<a class="title is-4" href="#" aria-current="page"><span class="icon is-small"><i class="fa fa-home"></i></span> Home</a>
				    </li>
				  </ul>
				</nav>
				<p>Welcome to the University of Alabama: Artificial Intelligence and Machine Learning [AI/ML] club. Join our growing club and participate in projects that interest you: mathematics, business, finance, science, and art. Interested in something else? Suggest a project. All majors are welcome!</p>

				<hr>

				<!-- Mailing List Form -->
				<h1 class="title is-4">Fill out the form to add yourself to our mailing list & Stay updated with all the latest information.</h1>
			
			<form action="" method="post">	
				{% csrf_token %}					
				<div class="columns">
					<div class="column">
						<div class="field">
							<label class="label">First Name</label>
							<div class="control">
							<input class="input" type="text" placeholder="First Name.."  name="firstName" maxlength="100" required="" id="id_firstName">
  						</div>
  					</div>
					</div>
					<div class="column">
						<div class="field">
							<label class="label">Last Name</label>
							<div class="control">
							<input  class="input" type="text" placeholder="Last Name.." name="lastName" maxlength="100" required="" id="id_lastName">								
  						</div>
						</div>
					</div>
				</div>

				<div class="field">
					<label class="label">Email</label>
					<div class="control is-expanded">
					<input class="input" type="email" name="email" maxlength="254" required="" id="id_email"  placeholder="Email..">
  					</div>
				</div>
				<input class="button is-danger is-outlined" type="submit" value="Add Me!">
				
			</form>
				


				<hr>

				<!-- Schedule -->
				<h1 class="title is-3">Schedule</h1>
				<p>Meeting dates this semester plus suggested schedule - open for edits/ideas! Checkpoints are for everyone to share progress on their projects and talk about their process. What do you think should go in the empty spots? Lessons in new techniques? Casual discussion meetings?</p>

				<br>

				<table class="table is-fullwidth">
					<thead>
						<tr>
							<th class="is-light">Date</th>
							<th class="is-light">Description</th>
							<th class="is-light">Location</th>
						</tr>
					</thead>
					<tbody>
						{% if schedule_list %}
						<ul>
							{% for schedule in schedule_list %}
							<tr>
								<td>{{ schedule.date }}</td>
								<td>{{ schedule.desc|linebreaks }}</td>
								<td>{{ schedule.loc }}</td>
							</tr>
							{% endfor %}
						{% else %}
						<p>No schedule are available.</p>
						{% endif %}

					</tbody>
				</table>

				<hr>

				<!-- Propose Event -->
				<h1 class="title is-3">Proposed Events</h1>
				<div class="content">
					<ul>
						<li>Moneyball screening</li>
						<li>Ex Machina</li>
						<li>Blade Runner</li>
						<li>Her</li>
						<li>Artificial Intelligence</li>
						<li>Margin Call</li>
						<li>The Imitation Game, 21, The Matrix</li>
						<li>A Beautiful Mind (Best Data Analysis and Machine Learning Movies)</li>
					</ul>
				</div>

			</div>

{% endblock %}

home/templates/thankYou.html
{% extends "base_generic.html" %}

{% block content %}
<div class="column section">
        
    <!-- Home -->
    <!-- <h1 class="title is-3">Home</h1> -->
    <nav class="breadcrumb is-large" aria-label="breadcrumbs">
        <ul>
        <li><a class="title is-4" href="{% url 'index' %}">AI & ML Club</a></li>
        <li class="is-active">
            <a class="title is-4" href="#" aria-current="page"><span class="icon is-small"><i class="fa fa-home"></i></span> Home</a>
        </li>
        </ul>
    </nav>
    <h3>Thank you for joining our e-mail list. You will be notified of future events and projects within the group. <br> If you need to get more information, e-mail aiclubua@gmail.com! </h3>

    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br>
    <br>
    <br>
    <br>
    
</div>
{% endblock %}