DjangoApp/urls.py
"""
Definition of urls for DjangoApp.
"""

from datetime import datetime
from django.conf.urls import url
# from app.forms import BootstrapAuthenticationForm
# from app.views import *
# from app.models import *
# from django.contrib.auth.views import *


# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
     
#     url(r'^$', home, name='home'),
#     url(r'^contact$', contact, name='contact'),
#     url(r'^about', about, name='about'),
#    url(r'^login/$', login, {
#             'template_name': 'app/login.html',
#             'authentication_form': BootstrapAuthenticationForm,
#             'extra_context':
#             {
#                 'title':'Log in',
#                 'year':datetime.now().year,
#             }
#         },
#         name='login'),
#        url(r'^logout$', logout, {  'next_page': '/'  },        name='logout')

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
]

# Use include() to add URLS from the catalog application 
from django.conf.urls import include

urlpatterns += [
    url(r'^home/', include('home.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^resources/', include('resources.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True)),
]


# Use static() to add url mapping to serve static files during development (only) 
#### I KNOW IT ONLY SAYS DURING DEVELOPMENT BUT I DONT KNOW WHERE ELSE TO PUT STATIC FILES (CSS)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#add image directory
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
]

projects/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='projects'),
    url(r'^(?P<project_id>[0-9]+)/$', views.showProject, name='showProject'), #regex is hard
]

uaMachineLearn/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application 
from django.conf.urls import include

urlpatterns += [
    url(r'^home/', include('home.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^resources/', include('resources.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#add image directory
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    project_name = models.CharField("Project Name", max_length=50, default="")
    pub_date = models.DateTimeField('Date Created')
    project_desc = models.TextField("Project Description", max_length=10000, default="")
    def __str__(self):
        return self.project_name
    
class BulletinPost(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    post_date = models.DateTimeField('Date Posted')
    post_user = models.CharField('Name', max_length=35)
    post_message = models.TextField('Message', max_length=10000)
    def __str__(self):
        return self.post_message 

projects/forms.py
from django import forms

from .models import Project, BulletinPost

from datetime import datetime

class PostForm(forms.ModelForm):
    class Meta: 
        model = BulletinPost
        fields = ['project', 'post_date', 'post_user', 'post_message' ]
        widgets = {
            'project': forms.HiddenInput(), 
            'post_date': forms.HiddenInput(),
            'post_user': forms.TextInput(attrs={
                'class': 'input is-primary',
            }),
            'post_message' :  forms.Textarea(attrs={'cols': 55, 'rows': 10}),
        }

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'pub_date': forms.HiddenInput(),
            'project_name': forms.TextInput(attrs={
                'class': 'input is-primary',
            }),
            'project_desc' :  forms.Textarea(attrs={'cols': 55, 'rows': 10}),
        }

projects/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.
from .models import Project 
from .forms  import ProjectForm, PostForm 
from datetime import datetime

'''
    Show the detailed project page, after clicking the project hyperlink
    Also, create the "Add a Bulletin Post" form
    Return projectDetail.html
'''
def showProject(request, project_id):
    index = project_id

    # set project to the correct index
    project = Project.objects.get(pk=index)
    
    # if this is a POST request we need to process the form data
    '''
        class BulletinPost(models.Model):
            project = models.ForeignKey(Project, on_delete=models.CASCADE)
            post_date = models.DateTimeField('Date Posted')
            post_user = models.CharField(max_length=35)
            post_message = models.CharField(max_length=140)
    '''
    if request.method == 'POST':
        form = PostForm(request.POST, )
        
        # after clicking "Submit" button, validate form and save to database if ok
        if form.is_valid():
            form.save()
            # refresh the page after submitting
            return HttpResponseRedirect('/projects/' + project_id)

    # if a GET (or any other method) we'll create a blank form
    # if we're creating a webpage, we'll create blank form
    # --Also, because we are hiding project and post_date, we must initialize it.
    # Not initializing it treats it as a null object ""VERY BAD""
    else:
        form = PostForm(initial={ 'project' : project, 'post_date': datetime.now(),}, )
    
    # context allows you to grab variabes from view onto the template.
    context = { 'project' : project, 'form': form }

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'projectDetail.html',
        context,
    )


def index(request):
    # if this is a POST request we need to process the form data
    '''
        ProjectForm() tells us to create a form with the ProjectForm Object
            class Project(models.Model):
            project_name = models.CharField(max_length=50, default="")
            pub_date = models.DateTimeField('Date Created')
            project_desc = models.CharField(max_length=10000, default="")
    '''
    if request.method == 'POST':
        form = ProjectForm(request.POST, )
        # after clicking "Submit" button, validate form and save to database if ok
        if form.is_valid():
            form.save()
            # refresh the page after submitting
            return HttpResponseRedirect('/projects/') 

    # if a GET (or any other method) we'll create a blank form
    # if we're creating a webpage, we'll create blank form
    # --Also, because we are hiding pub_date, we must initialize it.
    # Not initializing it treats it as a null object ""VERY BAD""
    else:
        
        form = ProjectForm(initial={ 'pub_date': datetime.now(),}, )

    # Enumerate all projects in alpha order by 'project name
    project_list = Project.objects.order_by('project_name')

    # context allows you to grab variabes from view onto the template.
    context ={ 'form': form, 'project_list': project_list, } 

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'projects.html',
        context,
    )

projects/templates/projectDetail.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'projects/css/custom.css' %}">
{% endblock %}

{% block content %}
{% load staticfiles %}

<div class="column section">

    <nav class="breadcrumb is-large" aria-label="breadcrumbs">
        <ul>
        <li><a class="title is-4" href="{% url 'index' %}">AI & ML Club</a></li>
        <li class="is-active">
            <a class="title is-4" href="#" aria-current="page"><span class="icon is-small"><i class="fa fa-briefcase"></i></span> Projects</a>
        </li>
        </ul>
    </nav>

    {% if project %}
    
    <div id="chat">
        <h1 class="title is-2 has-text-centered">    {{ project.project_name }}   </h1>
        
        <div class="card-header"><p class="card-header-title">{{ project.project_desc|linebreaksbr }} </p></div>
        <div id="chat-box" class="card">
          <div class="card-content">
            <div class="tile is-ancestor is-vertical">
            {% for bulletinPost in project.bulletinpost_set.all %}
            <div class="tile is-child">
                <article class="message is-dark">
                    <div class="message-header"><p>{{ bulletinPost.post_user }} </p></div>
                    <div class="message-body"><p>{{ bulletinPost.post_message|linebreaksbr }} </p></div>
                </article>
                <div class="date hidden">
                    <time datetime="">{{ bulletinPost.post_date }}</time>
                </div>
            </div>
            {% endfor %}
            <!-- Run Scripts AFTER it is looped over -->
            <script type="text/javascript" src="{% static 'projects/js/script.js' %}"></script>            
              
            </div>
          </div>
        </div>
        
        <form action="" method="post">
                {% csrf_token %}
            {{ form }}    
            <input class="button is-danger is-outlined" type="submit" value="Post Message">
        </form>
      </div>
   
    {% endif %}

</div>

{% endblock %}

projects/templates/projects.html
{% extends "base_generic.html" %}
{% load staticfiles %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'projects/css/custom.css' %}">
{% endblock %}

{% block content %}
<div class="column section">

    <nav class="breadcrumb is-large" aria-label="breadcrumbs">
        <ul>
        <li><a class="title is-4" href="{% url 'index' %}">AI & ML Club</a></li>
        <li class="is-active">
            <a class="title is-4" href="#" aria-current="page"><span class="icon is-small"><i class="fa fa-briefcase"></i></span> Projects</a>
        </li>
        </ul>
    </nav>
    <div>
    {% if project_list %}
    <ul>
    {% for project in project_list %}
        <li><a href="/projects/{{ project.id }}">{{ project.project_name }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No projects are available.</p>
    {% endif %}
    <form action="" method="post">
    {% csrf_token %}
        {{ form }}    
    <input class="button is-danger is-outlined" type="submit" value="Create Project (Reversible)">
    </form>
    </div>
</div>

{% endblock %}